---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chunk7-proof-secret
  namespace: ainulindale-sealed-secrets-proof
spec:
  encryptedData:
    chunk7_proof: AgBvt79NvldmWnT+5N7SySwJVELkEk/OKYUdHc+0EyBOJf5hG21OZM53NqhX95s+dQADXUuzOK0xMsR7+wJ8mGQtZAOm3uiMNGkkG9VOBeECflS56FFLAnj+Jwvxmsp5yo9XYo7n42OY2oytfFh+32DUdg0N6AEQp7xWH46g/4A3sYQddkWBKXLV4o+4fam1pUxGwG0rSqfc8r8vGZqW7feezlk0eQfOfqEGF4Gx/i4kYAz7NK0h7T/xY+q+yQP1WNN/jL906yB7/eJNZHCyX6LA9NCyUzzwbX92CY06yP+EbT44WD3TD/oei7fw845fFHNY8mVhbngbZ324nTT/99cWry03aWViztzTmHaz9mYmCy/YSg0WDKq8ZQIeYIep14jF462EA+HsLDCEGadJ/GzWXuM21r2Aly66FEPFQ1Q3x47x7rLF9h/MzgxCd6Qv6Fcg9Rfd7qdkVvgUNY8MFfdKE4e1zzxqXwfRK83qJVDTdOnsG5LxfwtMbguJKe1bc+0mtUGlOBdlg65YFsvYROI2plMEXF7O2VMzQyVQRIj0WtUO9U6KDzXA4zNvQstv+J90UXa+5mAUX9ejx140E0gYCKTlMGdEnK9GGTze340jpbp6+65FwCbyRVWtxTMueXAcyPaNSX24ra+oBGZFzaFW26vHRgvu6IUooNmPcfzZ87unt3+G7s9WygI82HalGVNpM3PGzpZKKbcMybfV6pPijJaCR1YbCS9wOzeHbZajl9NGprZ9QLi1WXR0a1Fpm7lC8Tt4OMM=
  template:
    metadata:
      name: chunk7-proof-secret
      namespace: ainulindale-sealed-secrets-proof
