apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealedsecret.yaml
images:
  - name: ghcr.io/dana/ainulindale-api
    newName: ghcr.io/dana/ainulindale-api
    newTag: manual-sha-placeholder

