---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ainulindale-api-runtime
  namespace: ainulindale-api
spec:
  encryptedData:
    chunk8_proof: AgCvfiVgPbe5R1izqDg4yB3K5jXrAUxw6reNVJQ93Opw0712xtq5UtBbac4sG0w8cEBCtkRvV5VRJ11e6R5O7BfXExZZvz/EkLlgijdo15r/7QxOnnXlKna/oFMKhq0w6g2t4lsYwzjzuwaKgaK+r0cLyLtgg6OITQzDwt4mSS08MgAkYjmUeeiTgRTS3E429GOZdCoRBuxJnm+wftAxOWdkL3rgF40s44UqL40sIemocbfpPD0WRivGpBMkgvIAO8ikx4ok/b4w4t389iEWT50K2HD6yoshX023baVhPEaYrJgYE/72EfDpLCbFYOTmG0iZqGihYoSHiK47Ge9NUXsQS2BAikJgojXfHofq6y0KBY3hZ3FH1wC949huoyoQ8moU2zCs0dPLu84ZKvsI5KI2OC45rPFp2qwygF0C5NI+mhCwMXk0M/0mW5KTsAjI7bnJ6uMi9mX4zhpXWdqs1p7VIRiVbns3ncoXQa3gD3Lii+vXURuzqNrcpGJ6LWYyY1VJNb9kPnzhzRIu4KweI83X9KyW7C3MxO9KTXnyrxFujFk+l+4nQWrVQ/CjMXlvFlh9Fnf+eXmkD/bPMnGBDFzUOWBNjxY5ePZ1/ViT5+IDNBo33QYv6gKN4eoDPl1yf0toY68NHKWLpg8cK1MUgKDodxeLQSRxYUaOUQjxknBU3SmqHAd3LJmranBWnAbPc6WV2MSRPAhWuY6XKQ/rPbQamFu1DKIVKlMYmIC8soDrPKtQlpwgmKJ3mJan
  template:
    metadata:
      name: ainulindale-api-runtime
      namespace: ainulindale-api
    type: Opaque
