apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/dana/ainulindale-api
  newName: ghcr.io/dana/ainulindale-api
  newTag: 266b6b98ce3b2ec6df9ce0884f8440ba3c94b281
