apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/dana/ainulindale-api
  newName: ghcr.io/dana/ainulindale-api
  newTag: 309051e66e409d7bc53e1745c799248e14dee051
