apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/dana/ainulindale-api
  newName: ghcr.io/dana/ainulindale-api
  newTag: c841534ff98ef215df00d87ed803ef6f7fa684b0
